package blatt8.genclient;


/**
* blatt8/gen/CorbaForumViewOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public interface CorbaForumViewOperations 
{
  void notifyView (blatt8.genclient.PositionedAvatar[] folks);
} // interface CorbaForumViewOperations
