package blatt8.genclient;


/**
* blatt8/gen/CorbaForumModelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public interface CorbaForumModelOperations 
{
  void registerView (String name, blatt8.genclient.CorbaForumView view) throws blatt8.genclient.AlreadyBoundException;
  void deregisterView (String name) throws blatt8.genclient.NotBoundException;
  void moveNorth (String name) throws blatt8.genclient.NotBoundException;
  void moveEast (String name) throws blatt8.genclient.NotBoundException;
  void moveSouth (String name) throws blatt8.genclient.NotBoundException;
  void moveWest (String name) throws blatt8.genclient.NotBoundException;
} // interface CorbaForumModelOperations
