package blatt8.genclient;


/**
* blatt8/gen/CorbaForumModel.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public interface CorbaForumModel extends CorbaForumModelOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CorbaForumModel
