package blatt8.genclient;

/**
* blatt8/gen/CorbaForumModelHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public final class CorbaForumModelHolder implements org.omg.CORBA.portable.Streamable
{
  public blatt8.genclient.CorbaForumModel value = null;

  public CorbaForumModelHolder ()
  {
  }

  public CorbaForumModelHolder (blatt8.genclient.CorbaForumModel initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = blatt8.genclient.CorbaForumModelHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    blatt8.genclient.CorbaForumModelHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return blatt8.genclient.CorbaForumModelHelper.type ();
  }

}
