package blatt8.genclient;


/**
* blatt8/gen/NotBoundException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public final class NotBoundException extends org.omg.CORBA.UserException
{

  public NotBoundException ()
  {
    super(NotBoundExceptionHelper.id());
  } // ctor


  public NotBoundException (String $reason)
  {
    super(NotBoundExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NotBoundException
