package blatt8.genclient;


/**
* blatt8/gen/Position.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public final class Position implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Position ()
  {
  } // ctor

  public Position (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Position
