package blatt8.genclient;

/**
* blatt8/gen/PositionedAvatarHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 11:18 Uhr MEZ
*/

public final class PositionedAvatarHolder implements org.omg.CORBA.portable.Streamable
{
  public blatt8.genclient.PositionedAvatar value = null;

  public PositionedAvatarHolder ()
  {
  }

  public PositionedAvatarHolder (blatt8.genclient.PositionedAvatar initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = blatt8.genclient.PositionedAvatarHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    blatt8.genclient.PositionedAvatarHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return blatt8.genclient.PositionedAvatarHelper.type ();
  }

}
