package blatt8.genserver;

/**
* blatt8/gen/AlreadyBoundExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 09:46 Uhr MEZ
*/

public final class AlreadyBoundExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public blatt8.genserver.AlreadyBoundException value = null;

  public AlreadyBoundExceptionHolder ()
  {
  }

  public AlreadyBoundExceptionHolder (blatt8.genserver.AlreadyBoundException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = blatt8.genserver.AlreadyBoundExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    blatt8.genserver.AlreadyBoundExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return blatt8.genserver.AlreadyBoundExceptionHelper.type ();
  }

}
