package blatt8.genserver;


/**
* blatt8/gen/CorbaForumModelHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 09:46 Uhr MEZ
*/

abstract public class CorbaForumModelHelper
{
  private static String  _id = "IDL:blatt8/gen/CorbaForumModel:1.0";

  public static void insert (org.omg.CORBA.Any a, blatt8.genserver.CorbaForumModel that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static blatt8.genserver.CorbaForumModel extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (blatt8.genserver.CorbaForumModelHelper.id (), "CorbaForumModel");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static blatt8.genserver.CorbaForumModel read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CorbaForumModelStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, blatt8.genserver.CorbaForumModel value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static blatt8.genserver.CorbaForumModel narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof blatt8.genserver.CorbaForumModel)
      return (blatt8.genserver.CorbaForumModel)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      blatt8.genserver._CorbaForumModelStub stub = new blatt8.genserver._CorbaForumModelStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static blatt8.genserver.CorbaForumModel unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof blatt8.genserver.CorbaForumModel)
      return (blatt8.genserver.CorbaForumModel)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      blatt8.genserver._CorbaForumModelStub stub = new blatt8.genserver._CorbaForumModelStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
