package blatt8.genserver;


/**
* blatt8/gen/CorbaForumViewPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 09:46 Uhr MEZ
*/

public abstract class CorbaForumViewPOA extends org.omg.PortableServer.Servant
 implements blatt8.genserver.CorbaForumViewOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("notifyView", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // blatt8/gen/CorbaForumView/notifyView
       {
         blatt8.genserver.PositionedAvatar folks[] = blatt8.genserver.FolksHelper.read (in);
         this.notifyView (folks);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:blatt8/gen/CorbaForumView:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CorbaForumView _this() 
  {
    return CorbaForumViewHelper.narrow(
    super._this_object());
  }

  public CorbaForumView _this(org.omg.CORBA.ORB orb) 
  {
    return CorbaForumViewHelper.narrow(
    super._this_object(orb));
  }


} // class CorbaForumViewPOA
