package blatt8.genserver;


/**
* blatt8/gen/CorbaForumModelOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from forum.idl
* Mittwoch, 11. Dezember 2013 09:46 Uhr MEZ
*/

public interface CorbaForumModelOperations 
{
  void registerView (String name, blatt8.genserver.CorbaForumView view) throws blatt8.genserver.AlreadyBoundException;
  void deregisterView (String name) throws blatt8.genserver.NotBoundException;
  void moveNorth (String name) throws blatt8.genserver.NotBoundException;
  void moveEast (String name) throws blatt8.genserver.NotBoundException;
  void moveSouth (String name) throws blatt8.genserver.NotBoundException;
  void moveWest (String name) throws blatt8.genserver.NotBoundException;
} // interface CorbaForumModelOperations
